### ISSUE TITLE
Troubles getting the code to compile

### ISSUE THREAD

**Issue by DirtyEngineer** [SensorsIot/HotGlueGunSwitch#1]
I tried to compile the code for this project and got several error messages.

**HotGlueGunSwitch.ino: In function 'void setup()':
HotGlueGunSwitch:65: error: 'EEPROMReadlong' was not declared in this scope
HotGlueGunSwitch.ino: In function 'void loop()':
HotGlueGunSwitch:117: error: 'FACTOR' was not declared in this scope
HotGlueGunSwitch.ino: In function 'void progTimer()':
HotGlueGunSwitch:175: error: too few arguments to function 'void digitalWrite(uint8_t, uint8_t)'
In file included from HotGlueGunSwitch.ino:43:0:
C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino/Arduino.h:126:6: note: declared here
 void digitalWrite(uint8_t, uint8_t);
      ^
HotGlueGunSwitch:175: error: expected ';' before ')' token
HotGlueGunSwitch:179: error: 'adress1' was not declared in this scope
HotGlueGunSwitch:179: error: 'EEPROMWritelong' was not declared in this scope
HotGlueGunSwitch:180: error: 'adress1' was not declared in this scope
HotGlueGunSwitch:180: error: 'EEPROMWritelong' was not declared in this scope
HotGlueGunSwitch:183: error: too few arguments to function 'void digitalWrite(uint8_t, uint8_t)'
In file included from HotGlueGunSwitch.ino:43:0:
C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino/Arduino.h:126:6: note: declared here
 void digitalWrite(uint8_t, uint8_t);
      ^
HotGlueGunSwitch:183: error: expected ';' before ')' token
HotGlueGunSwitch:187: error: 'adress2' was not declared in this scope
HotGlueGunSwitch:187: error: 'EEPROMWritelong' was not declared in this scope
'EEPROMReadlong' was not declared in this scope**

I was able to fix the "adress1/2" error by simply adding the missing "d"
The EEPROM errors are a little beyond me.

**Comment by SensorsIot** [comment]
I had the wrong code version uploaded. Now it should work. I am sorry for this mistake
